learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path # allows us to create/use URLS
from . import views # imports the views.py module (to link views with the URLs below)

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # the empty string represents the base url (http://127.0.0.1:8000/), which django ignores
    # so essentially, we are defining the view that will be displayed if a user arrives at the home page
    # we also name this home page "index", which lets us refer to this later elsewhere
    
    path('topics/', views.topics, name='topics'),
    # adding a topics url in the path <base_url>/topics/
    # view for this is defined in learning_logs/views.py module, just like index
    
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # adds a dynamic url created for every topic page <int:topic_id>
    # 
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # default paths are already defined, i.e. the admin path

    path('', include('learning_logs.urls')),
    # this allows paths defined in the urls.py module in learning_logs (which needs to be created) to be used here
]

learning_logs/models.py
from django.db import models

# Create your models here.

"""
What is a model? 
A model is a class
It tells django how to work with data we have stored in our database
As with other classes, it will have its own fields/methods
"""

# example model: 
"""A topic the user is learning about."""
class Topic(models.Model): # model class "Topic"; inheritance happens here, Topic inherits from the class "Model", which is built in and we import it above
# allows this class to use all the methods in "Model", as if they were "Topic"s own methods

    text = models.CharField(max_length=200) # note that we are specifying the text max size, must be 200 chars or less
    date_added = models.DateTimeField(auto_now_add=True)
    # these two lines add a text field and a date time field to our application
    # the basic building blocks of this is already defined in Models
    # Note these are not UI elements but rather columns in a SQL database (text is one, date_added is another)
    # we are simply defining what can go inside these two columns here
    
    # other addable columns exist, they can be seen here: https://docs.djangoproject.com/en/4.1/ref/models/fields (replace 4.1 with latest django version)
    
"""Return a string representation of the model."""
def __str__(self):
    return self.text
# the python equivalent of a toString() method in other languages
# whenever we need to convert a Topic object to a string (i.e. to make it human readable), this __str__ method will be called by default

"""Something specific learned about a topic."""
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    # ForeignKey is a database concept
    # Every table created in a database has a key
    # To link one table to another, we use these keys
    # meaning if we wanted to link an "Entry" object to a "Topic" object, we would use the Topic's key here (this would be the Entry's foreign key) 
    
    # on_delete=models.CASCADE means that if a Topic gets deleted, all associated Entrys with that topic will also be deleted
    
    text = models.TextField() # no size limit this time
    date_added = models.DateTimeField(auto_now_add=True)
    # adding a text column and date_added column for each Entry, just as we did with Topics
    
    class Meta:
        verbose_name_plural = 'entries'
        # tells django to rever to multiple Entry objects as "entries", not "Entrys", which is the default if we had not added this line
        # this is more for user readability than anything

    """Return a simple string representing the entry."""
    def __str__(self):
        return f"{self.text[:50]}..."
    # If we needed to convert an Entry object to a String, this is how we would do it
    # we additionally specify that we want only the first 50 characters of the text of the Entry object when converting to a string

learning_logs/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')
    # creating an index view here 
    # when a user tries to access the index path (defined in urls.py in learning logs), they will be shown an HTML page
    # defined in index.html, which needs to be made
        # note that the path should be /<app_folder>/templates/learning_logs/index.html
        # so "learning_logs/templates/learning_logs/index.html" in this case

def topics(request):
    """Topics page (view)"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    # adding information needed to properly render the Topics page
    
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)
    # adding information needed to properly render an individual Topic page

learning_logs/templates/learning_logs/base.html
<!-- This is a base page; other templates will inherit (and display) the elements shown here -->
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <!--Link to the home (base url) page-->
</p>
    
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <!--Another link to the home page-->
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
    <!--Links to each individual topic (for use primarily in /topics)-->
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
<!-- Specifying that this html file will inherit from base.html; it will display the same elements displayed in base.html without us having to repeat them-->

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you'reinterested in.</p>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
<!--Inherit from (extend) base.html-->
{% block content %}
<p>Topic: {{ topic.text }}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>
    {% empty %}
    <!--Looping through and displaying each and every Entry under a Topic, with both date and time added-->
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
<!--Inherits from base.html-->
{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}</a>
    </li>
    <!--makes each Topic text a clickable link, to go to that topics Topic page-->
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<!-- Uses a for loop (for topic in topics) to take each individual topic (provided in views.py) and display them in an <li> tag on the page -->


{% endblock content %}